app = "osmo-warehouse"  # Zmień na nazwę swojej aplikacji
primary_region = "waw"  # Zmień na swój region, np. waw dla Warszawy

[build]
  image = ""  # Fly.io wygeneruje obraz na podstawie Dockerfile lub kodu

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true

[[services.ports]]
  handlers = ["http"]
  port = 80

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443

[checks]
  [checks.http_check]
    port = 8080
    type = "http"
    path = "/"
    interval = "30s"
    timeout = "5s"
